# Generated by Django 5.1.7 on 2025-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='Item_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Name',
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='item_name',
            field=models.CharField(default='Default Item Name', max_length=250),
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='Default Item Name', max_length=255),
        ),
    ]
