# Generated by Django 5.1.7 on 2025-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_items_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='item_name',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
